package com.archapp.coresmash;

public enum NotificationType {
    NULL,
    NOTIFICATION_TYPE_TILE_DESTROYED,
    BALL_LAUNCHED,
    NOTIFICATION_TYPE_MOVINGTILE_COLLIDED,
    NO_COLOR_MATCH,
    SAME_COLOR_MATCH,
    NOTIFICATION_TYPE_CENTER_TILE_DESRTOYED,
    NOTIFICATION_TYPE_NEW_TILE_CREATED,

    NOTIFICATION_TYPE_SCORE_INCREMENTED,
    NOTIFICATION_TYPE_STREAK_3X,
    NOTIFICATION_TYPE_STREAK_4X,
    NOTIFICATION_TYPE_STREAK_5X,

    TILEMAP_INITIALIZED,
    NOTIFICATION_TYPE_LIVES_CHANGED,
    MOVES_AMOUNT_CHANGED,
    NOTIFICATION_TYPE_PATH_TO_CENTER_OBSTRUCTED,
    COLOR_MATCHES_FINISHED,
}
