package com.breakthecore;

public enum NotificationType {
    NULL,
    NOTIFICATION_TYPE_TILE_DESTROYED,
    NOTIFICATION_TYPE_MOVINGTILE_COLLIDED,
    NO_COLOR_MATCH,
    SAME_COLOR_MATCH,
    NOTIFICATION_TYPE_CENTER_TILE_DESRTOYED,
    NOTIFICATION_TYPE_NEW_TILE_CREATED,

    NOTIFICATION_TYPE_SCORE_INCREMENTED,
    NOTIFICATION_TYPE_STREAK_3X,
    NOTIFICATION_TYPE_STREAK_4X,
    NOTIFICATION_TYPE_STREAK_5X,

    NOTIFICATION_TYPE_LIVES_CHANGED,

    NOTIFICATION_TYPE_PATH_TO_CENTER_OBSTRUCTED,
}
