package com.breakthecore;

public enum NotificationType {
    NULL,
    NOTIFICATION_TYPE_TILE_DESTROYED,
    NOTIFICATION_TYPE_MOVING_TILE_COLLIDED,
    NOTIFICATION_TYPE_CENTER_TILE_DESRTOYED,
    NOTIFICATION_TYPE_NEW_TILE_CREATED
}
